services:
  scaia:
    build: .
    container_name: scaia
    ports:
      - "8501:8501"
    volumes:
      - ./vectorstore:/app/vectorstore
      - ./images:/app/images
      - ./prompts:/app/prompts
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    restart: unless-stopped
